apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-b-app
  namespace: team-b
spec:
  replicas: 2
  selector:
    matchLabels:
      app: team-b-app
  template:
    metadata:
      labels:
        app: team-b-app
    spec:
      containers:
        - name: app
          image: mkhattab77/privatemultiuser:team-b-app
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
      imagePullSecrets:
        - name: regcred 