apiVersion: v1
kind: Service
metadata:
  name: team-b-service
  namespace: team-b
spec:
  selector:
    app: team-b-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP 