apiVersion: v1
kind: ResourceQuota
metadata:
  name: team-b-quota
  namespace: team-b
spec:
  hard:
    pods: "2"
    requests.cpu: "100m"
    requests.memory: "64Mi"
    limits.cpu: "200m"
    limits.memory: "256Mi" 