apiVersion: v1
kind: ResourceQuota
metadata:
  name: team-a-quota
  namespace: team-a
spec:
  hard:
    pods: "2"
    requests.cpu: "100m"
    requests.memory: "64Mi"
    limits.cpu: "200m"
    limits.memory: "256Mi"