apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: team-b-rolebinding
  namespace: team-b
subjects:
  - kind: User
    name: team-b-user
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: team-b-role
  apiGroup: rbac.authorization.k8s.io 