apiVersion: v1
kind: Service
metadata:
  name: team-a-service
  namespace: team-a
spec:
  selector:
    app: team-a-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer 