name: CI/CD for Team A

on:
  push:
    branches: [ main ]
    paths:
      - 'team-a/**'
      - '.github/workflows/team-a-ci-cd.yaml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./team-a
          file: ./team-a/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/privatemultiuser:team-a-app

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:  us-east-1

      - name: Set up kubectl for EKS
        run: |
          aws eks update-kubeconfig --name eks-1 --region us-east-1

      - name: Deploy to Kubernetes
        run: |
          # Kubeconfig is now managed by 'aws eks update-kubeconfig'
          kubectl apply -f kubernetes-config/namespaces/team-a-namespace.yaml
          kubectl apply -f kubernetes-config/rbac/team-a-role.yaml
          kubectl apply -f kubernetes-config/rbac/team-a-rolebinding.yaml
          kubectl apply -f kubernetes-config/resource-quotas/team-a-quota.yaml
          kubectl apply -f kubernetes-config/network-policies/team-a-network-policy.yaml
          kubectl apply -f team-a/k8s/deployment.yaml
          kubectl apply -f team-a/k8s/service.yaml 